server:
  port: 10001

logging:
  level:
    com.oracle.mapper: debug # 配置日志

spring:
  datasource:
    username: root
    password: 200111
    url: jdbc:mysql://127.0.0.1:3306/oa?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver


